python 1st_floor_AB_interior_double_plate.py > 1st_floor_AB_interior_double_plate_results.txt
python 1st_floor_interior_double_plate.py > 1st_floor_interior_double_plate_results.txt
python 2nd_floor_AB_interior_double_plate.py > 2nd_floor_AB_interior_double_plate_results.txt
python 2nd_floor_interior_double_plate.py > 2nd_floor_interior_double_plate_results.txt
python 3rd_floor_AB_interior_double_plate.py > 3rd_floor_AB_interior_double_plate_results.txt
python 3rd_floor_interior_double_plate.py > 3rd_floor_interior_double_plate_results.txt

