Dead_LC=lcases.LoadCase(preprocessor=prep,name="Dead_LC",loadPType="default",timeSType="constant_ts")
Dead_LC.create()
Dead_LC.addLstLoads([selfWeight,Dead2F,Dead1F,Earth1F,earthPressEastwall,earthPressWestwall,DeadSB,DeadCW,DeadCC,DeadCE])
'''
modelSpace.addLoadCaseToDomain("Dead_LC")
out.displayLoadVectors()
out.displayLoads(beams)
modelSpace.removeLoadCaseFromDomain("Dead_LC")
'''

Live_LC=lcases.LoadCase(preprocessor=prep,name="Live_LC",loadPType="default",timeSType="constant_ts")
Live_LC.create()
Live_LC.addLstLoads([Live2F,Live1F,LiveSB,LiveCW,LiveCC,LiveCE])
'''
modelSpace.addLoadCaseToDomain("Live_LC")
out.displayLoadVectors()
out.displayLoads(beams)
modelSpace.removeLoadCaseFromDomain("Live_LC")
'''
Snow_LC=lcases.LoadCase(preprocessor=prep,name="Snow_LC",loadPType="default",timeSType="constant_ts")
Snow_LC.create()
Snow_LC.addLstLoads([Snow2F,Snow1F,SnowSB,SnowCW,SnowCC,SnowCE])
'''
modelSpace.addLoadCaseToDomain("Snow_LC")
out.displayLoadVectors()
out.displayLoads(beams)
modelSpace.removeLoadCaseFromDomain("Snow_LC")
'''

Wind_LC=lcases.LoadCase(preprocessor=prep,name="Wind_LC",loadPType="default",timeSType="constant_ts")
Wind_LC.create()
Wind_LC.addLstLoads([Wind2F,Wind1F,HWind2F])
'''
modelSpace.addLoadCaseToDomain("Wind_LC")
out.displayLoadVectors()
out.displayLoads(beams)
modelSpace.removeLoadCaseFromDomain("Wind_LC")
'''
