combContainer= cc.CombContainer()  #Container of load combinations
combContainer.ULS.perm.add('ULS01', '1.4*DeadL')
combContainer.ULS.perm.add('ULS02_a', '1.2*DeadL + 1.6*LiveL_ru + 1.0*LiveL_pu + 0.5*SnowL')
combContainer.ULS.perm.add('ULS02_b', '1.2*DeadL + 1.6*LiveL_rs + 1.0*LiveL_ps + 0.5*SnowL')
combContainer.ULS.perm.add('ULS03_a', '1.2*DeadL + 1.6*SnowL + 0.5*LiveL_ru + 1.0*LiveL_pu')
combContainer.ULS.perm.add('ULS03_b', '1.2*DeadL + 1.6*SnowL + 0.5*LiveL_rs + 1.0*LiveL_ps')
combContainer.ULS.perm.add('ULS04_a', '1.2*DeadL + 1.6*SnowL + 0.5*Wind_WE')
combContainer.ULS.perm.add('ULS04_b', '1.2*DeadL + 1.6*SnowL + 0.5*Wind_NS')
combContainer.ULS.perm.add('ULS05_a', '1.2*DeadL + 1.0*Wind_WE + 0.5*LiveL_ru + 1.0*LiveL_pu')
combContainer.ULS.perm.add('ULS05_b', '1.2*DeadL + 1.0*Wind_NS + 0.5*LiveL_ru + 1.0*LiveL_pu')
combContainer.ULS.perm.add('ULS05_c', '1.2*DeadL + 1.0*Wind_WE + 0.5*LiveL_rs + 1.0*LiveL_ps')
combContainer.ULS.perm.add('ULS05_d', '1.2*DeadL + 1.0*Wind_NS + 0.5*LiveL_rs + 1.0*LiveL_ps')
combContainer.ULS.perm.add('ULS06_a', '1.2*DeadL + 0.5*LiveL_ru + 1.0*LiveL_pu + 0.2*SnowL')
combContainer.ULS.perm.add('ULS06_b', '1.2*DeadL + 0.5*LiveL_rs + 1.0*LiveL_ps + 0.2*SnowL')
combContainer.ULS.perm.add('ULS07_a', '0.9*DeadL + 1.0*Wind_WE')
combContainer.ULS.perm.add('ULS07_b', '0.9*DeadL + 1.0*Wind_NS')
